### ISSUE TITLE
AttributeError: module 'base64' has no attribute 'decodestring' with Python 3.9.2

### ISSUE THREAD

**Issue by githuzzel** [harpyeagle/landroid-pi-influx#1]
Hi,

Im gettig the follow error:

2022-08-22 11:02:09 __init__ _api_authentificate INFO     Successfully logged in
Traceback (most recent call last):
  File "/home/raspi/python/landi.py", line 15, in <module>
    landroid.connect("<myuser>", "<mypassword>")
  File "/usr/local/lib/python3.9/dist-packages/landroidcc/__init__.py", line 74, in connect
    self._connectmqtt()
  File "/usr/local/lib/python3.9/dist-packages/landroidcc/__init__.py", line 135, in _connectmqtt
    pkcs12 = base64.decodestring(self._api_certificate["pkcs12"].encode())
AttributeError: module 'base64' has no attribute 'decodestring'

Python 3.9.2

**Comment by harpyeagle** [comment]
Can you try updating your packages?

**Comment by githuzzel** [comment]
the updated one is working fine. But the one, which will be delivered with PIP is not working.
